version: '3.0'
volumes:
  torvalds-network:
  gittoken-server:
  mysql-volume:
services:
  mysql:
    ports:
      - 3306:3306
    env_file:
      - mysql.env
    volumes:
      - mysql-volume:/var/lib/mysql
    image:
      mysql
  gittoken:
    ports:
      - 4242:3000
    env_file:
      - gittoken.env
      - mysql.env
    build:
      context: .
    volumes:
      - gittoken-server:/mnt/gittoken
  torvalds:
    ports:
      - 5180:8180
      - 5545:8545
      - 5546:8546
      - 30305:30303
    build:
      context: ./torvalds/.
    volumes:
      - torvalds-network:/mnt/parity
    command: --config /mnt/parity/config.toml
