version: '3.0'
services:
  gittoken:
    ports:
      - 1324:1324
      - 1325:1325
    image: "gittoken/express-server:v1"
  parity:
    ports:
      - 8080:8080
      - 8180:8180
      - 8545:8545
      - 30303:30303
    image: "parity/parity:v1.6.8"
    volumes:
      # Ensure volume paths are correct on host; e.g. the following assumes
      # the docker host has pulled this repo at the location,
      # `~/.gittoken/express-server`, and has a valid config file located within
      # the /parity subdirectory
      - /home/ryan/.gittoken/express-server/parity/:/mnt/
    command: --reseal-min-period 0 --gasprice 0 --rpccorsdomain="*" --geth --config /mnt/config.toml
